### ISSUE TITLE
Highlight breaks as the cursor moves

### ISSUE THREAD

**Issue by tami5** [sogaiu/tree-sitter-clojure#10]
Hey @sogaiu , I'm facing this wired issue with tree-sitter that I don't usually experience with other languages.
Basically, the highlight breaks as the cursor moves, which always the case when using macros

![treesiteer-clojure](https://user-images.githubusercontent.com/65782666/100642405-ca9f5180-3349-11eb-877c-508e1109af9e.gif)

- Neovim version: `NVIM v0.5.0-891-gaec61074a`
- nvim-treesitter: `ab808e8`

Thanks

**Comment by sogaiu** [comment]
@tami5 My initial impression is that this is not likely to be an issue with the grammar itself.

I would recommend asking the nvim-treesitter folks for advice.  In addition to their github repository, there is also: https://nvim-treesitter.zulipchat.com if you are so inclined.  I have found them to be a friendly and helpful group of folks.

**Comment by tami5** [comment]
Thanks a lot @sogaiu

**Comment by tami5** [comment]
Thanks a lot @sogaiu
