### ISSUE TITLE
The function `f` given as argument to `update` isn't highlighted as a function

### ISSUE THREAD

**Issue by oryband** [sogaiu/tree-sitter-clojure#15]
See example:
![image](https://user-images.githubusercontent.com/115387/125674639-e6c93947-f235-40db-9beb-7b4151d56e3c.png)

**Comment by oryband** [comment]
Might be worth checking this in sibling functions such as `update-in` etc.

**Comment by sogaiu** [comment]
I'm going to close this as I think the issue lies elsewhere, but if it turns out otherwise, it can be reopened.
