### ISSUE TITLE
tree-sitter web-ui doesn't show parse tree in right pane

### ISSUE THREAD

**Issue by sogaiu** [sogaiu/tree-sitter-clojure#17]
IIUC, according to [a comment in the "Doesn't seem to update with treesitter playground" issue](https://github.com/tree-sitter/tree-sitter-haskell/issues/35#issuecomment-857387920) a related factor may be a version mismatch for emsdk.

It may be that for tree-sitter-cli version 0.19.3, using [version 2.0.11 of emsdk](https://github.com/tree-sitter/tree-sitter/commit/b14ea51e3df4f5614d8913513a4d1eed8be07d71#diff-984521346618aa0769f8893285c0818ce673896f640bd3f2b606acb047f11c71) works.

For tree-sitter-cli version 0.19.5, using [version 2.0.24 of emsdk](https://github.com/tree-sitter/tree-sitter/commit/a286f831c749d1cb00d577cceb19d28c9d0f3338#diff-984521346618aa0769f8893285c0818ce673896f640bd3f2b606acb047f11c71) may work.

**Comment by NoahTheDuke** [comment]
Upgrading to `tree-sitter-cli` 0.20.6 (the latest version) fixes this.

**Comment by sogaiu** [comment]
Thanks for sharing!

**Comment by sogaiu** [comment]
On the topic of versions of emsdk, it appears that versions from (and above?) 2.0.18 may have issues currently: https://github.com/tree-sitter/tree-sitter/issues/1098#issuecomment-842326203

**Comment by NoahTheDuke** [comment]
All these issues make the tree-sitter ecosystem feel _really_ fragile. Not your fault, of course, I'm just surprised and disappointed.

**Comment by sogaiu** [comment]
I'm hoping things will improve somewhat over time -- though I don't expect that to be soon.

For reference, there is this [1.0 Checklist](https://github.com/tree-sitter/tree-sitter/issues/930).

**Comment by sogaiu** [comment]
I've been examining the tree-sitter repository's commit logs and source recently and my current impression is that the fragility stems from at least a few factors:

1. Use of emscripten - I think that's a neat project and have used it myself, but stability of API has not been something they've promised (AFAIU).  I don't think there's really a good alternative to emscripten (at least not from a licensing perspective) at the current time and I'd much rather have some option than none.
2. Use of npm / Node.js - Almost every grammar repository uses a project structure and tooling that makes use of these bits.  May be I don't need to go into why this can contribute to instability.

On a related note, I have experimented with a structure that removes the use of `npm` recently.  I've discovered that the tree-sitter command line tool is built to generate various binding files (for Node.js and Rust) and it is hard-wired to look for `package.json` to carry out at least one subcommand.

I think it's possible to stop using `npm` though and that's something I'm still exploring.

**Comment by sogaiu** [comment]
I think it's pretty clear that the original issue is caused by version mismatches between emscripten and the tree-sitter cli.

It would be nicer if the official docs (e.g. [these](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-6-contributing.md)) stated version requirements in detail (and there have been comments at the tree-sitter repository about this from time to time).

At present, if one uses a recent post 0.20.7 version of the tree-sitter cli (e.g. by compiling from source), [emscripten 3.1.29 works](https://github.com/tree-sitter/tree-sitter/commit/88fe1d00c42760beda7cc01f5259da3d7fc5265e).  I've been using it with no obvious issues.

I'm going to close this issue as it's not specific to tree-sitter-clojure and I'm not sure it helps to keep it open.  If someone feels otherwise though, I'm willing to discuss :)

**Comment by sogaiu** [comment]
I think this issue may resurface from time to time.

I've written up some details on it [here](https://github.com/sogaiu/ts-questions/blob/master/questions/which-version-of-emscripten-should-be-used-for-the-playground/README.md) for future reference.
