### ISSUE TITLE
Midje metaconstants are displayed as TSMethod even though they are constants

### ISSUE THREAD

**Issue by oryband** [sogaiu/tree-sitter-clojure#18]
Midje provides the notion of [metaconstants](https://github.com/marick/Midje/wiki/Metaconstants), and they are defined by surrounding words using double periods or dashes e.g. `..my-metaconstant..` or `--my-metaconstant--`. Treesitter-clojure highlights them as methods, specifically if they are written on their own. Also if they are the second element in a list i.e. the first argument to a function. However, if they are the third list element (second function argument), they get the Variable group.

See the following screenshot:
![image](https://user-images.githubusercontent.com/115387/147081212-5a4d3f92-8560-4910-92e1-f6b31a299bfd.png)
![image](https://user-images.githubusercontent.com/115387/147081252-2939f52b-f898-4a83-9cf0-9fb961c6f793.png)
![image](https://user-images.githubusercontent.com/115387/147081306-eaf964f1-1e42-4912-9066-678574873f78.png)

**Comment by oryband** [comment]
I think is happening because of the two prepending periods. It's not related to Midje at all.

**Comment by sogaiu** [comment]
Thanks for the report.

IIUC, the behavior described is in the context of nvim-treesitter.  Is that correct?

Assuming so, I think the way highlighting behaves there depends on [this nvim-treesitter file](https://github.com/nvim-treesitter/nvim-treesitter/blob/56634f49ab3d8122153c8c5582c581fb6a6af075/queries/clojure/highlights.scm) -- though I suppose the version you have may be different.

As an initial guess, may be it's [around here](https://github.com/nvim-treesitter/nvim-treesitter/blob/56634f49ab3d8122153c8c5582c581fb6a6af075/queries/clojure/highlights.scm#L85-L96) that might be relevant.

It's true that I was involved in the creation of that file, but the current version appears to be much more the work of other contributors.  At least, that's what [the history](https://github.com/nvim-treesitter/nvim-treesitter/commits/011ac894ec5b9e36563d8629fb7734f43ddb27a8/queries/clojure/highlights.scm) of that file suggests to me.  

I haven't been following nvim-treesitter development very closely these days so I'm not sure whether there's a current preferred way to communicate about these types of issues.  At one point there was a fairly active community at nvim-treesitter's Zulip presence -- I think there may also be some gitter presence.  Another option might be nvim-treesitter's github repository.

**Comment by sogaiu** [comment]
I'm going to close this as I think the issue lies elsewhere, but if it turns out otherwise, it can be reopened.
