### ISSUE TITLE
Remove dependency on web-tree-sitter

### ISSUE THREAD

**Issue by wenkokke** [sogaiu/tree-sitter-clojure#19]
In general, tree-sitter parsers do not list web-tree-sitter in their dependencies.

I don't think the dependency is actually used. 

Would it make sense to remove it?

**Comment by sogaiu** [comment]
@wenkokke I did some testing with the dependency removed and didn't notice any issues.  The latest commit should have the dependency removed.

If it's working to your satisfaction, please close the issue.

Thanks for the report :)
