### ISSUE TITLE
Cutting a new tag off of master

### ISSUE THREAD

**Issue by Will-Sommers** [sogaiu/tree-sitter-clojure#23]
Hi y'all! 

Thank you! We rely on this package for Clojure support in [Cursorless](cursorless.org/), a voice-coding structural editing extension for VSCode. We're currently relying on the main branch but would like to peg our dependency against a version. Would y'all be up for creating a version `0.0.9`?

Thank you!

Also, I'm happy to send y'all a blurb on how Cursorless uses Clojure if you would like to add it to your docs.

**Comment by sogaiu** [comment]
@Will-Sommers I've [mentioned Cursorless in the docs](https://github.com/sogaiu/tree-sitter-clojure/blob/e57c569ae332ca365da623712ae1f50f84daeae2/doc/use.md) and tagged e57c569ae332ca365da623712ae1f50f84daeae2 as 0.0.9.

**Comment by Will-Sommers** [comment]
Thanks!
