### ISSUE TITLE
Smarter/more specific parsing

### ISSUE THREAD

**Issue by NoahTheDuke** [sogaiu/tree-sitter-clojure#25]
How interested are you in adding parsing for `clojure.core` special forms and macros to give highlighting and local variables more information?

**Comment by sogaiu** [comment]
In short, with the current capabilities of tree-sitter, I'm not interested in undertaking this.

There is a bit more detail about this summarized here: https://github.com/sogaiu/tree-sitter-clojure/blob/master/doc/scope.md

**Comment by NoahTheDuke** [comment]
Ah, I don't know how I missed that! Thanks for pointing it out. Makes a lot of sense. I'll close this then.
