### ISSUE TITLE
Why does `let` have different highlighting than `if-let` or from `when?

### ISSUE THREAD

**Issue by Invertisment** [sogaiu/tree-sitter-clojure#27]
These are all macros but `let` is blue... why is that? They're all macros and they're all declared in the `core` namespace. Weird.

![image](https://user-images.githubusercontent.com/1641263/187204053-4adf01bc-155a-492e-8843-216ff1031eb1.png)

**Comment by NoahTheDuke** [comment]
I believe most/all highlighting is delegated to the treesitter provider plugins (treesitter-nvim, etc).

**Comment by Invertisment** [comment]
So do you want to say that this plugin doesn't completely control the keywords it parses? :thinking:

**Comment by NoahTheDuke** [comment]
I'm not sure what you mean by "completely control the keywords", but this grammer deliberately doesn't try to do any semantic parsing, only syntactic. The [doc/scope.md](https://github.com/sogaiu/tree-sitter-clojure/blob/master/doc/scope.md) file has an explanation.

This means that provider plugins have to do that work themselves. For example, [nvim-treesitter's clojure highlighting](https://github.com/nvim-treesitter/nvim-treesitter/blob/f3c53d225ada93a99bfd818e1c40012400e2dc55/queries/clojure/highlights.scm) highlights `let` as a macro and the regex `"^if(\\-.*)?$"` and `"^when(\\-.*)?$")` as conditionals. This means it grabs both `if` and `if-let` and `when` and `when-let`, which I expect is the result you're seeing here.

So to fix this, either redefine these in the necessary `highlighting.scm` file on your machine or open an issue/PR for nvim-treesitter.

**Comment by Invertisment** [comment]
I see. For me I didn't think about `let` and `when-let` as being different type of constructs and I was often simply migrating between them so I didn't see a need for separate highlighting. But after not finding any keywords like that in this repository I didn't know where to look for information.

I do use nvim.
I'll try to look into that repo.

**Comment by Invertisment** [comment]
So basically this treesitter support doesn't provide more things than this plugin:

https://github.com/clojure-vim/clojure.vim/blob/master/syntax/clojure.vim#L35

If they have hardcoded the list of keywords then I'm not sure what's the benefit... They don't even highlight macros differently.

**Comment by Invertisment** [comment]
Also do you know what's about the bolding of all of the first elements of invocations? It's too much bold on the screen. It's not needed.

**Comment by sogaiu** [comment]
@Invertisment Sorry I don't really know the details of what nvim-treesitter does, though I know a number of different folks have contributed to the highlighting in nvim-treesitter.  Specifically, there are 6 contributors listed at the top of: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/clojure/highlights.scm -- perhaps one or more of them might know.

Regarding your earlier remark about not highlighting your macros, I believe that is a limitation of tree-sitter.  I don't think tree-sitter's author had languages like lisps (i.e. those that can effectively extend their syntax without changing their specifications) in mind when he designed tree-sitter.
