### ISSUE TITLE
How can I add keyword and namespace highlighting?

### ISSUE THREAD

**Issue by Invertisment** [sogaiu/tree-sitter-clojure#28]
What would be a way to add the highlighting that is described in this github issue: https://github.com/clojure-vim/clojure.vim/issues/24?

`kwd_lit` already captures whole keyword but I can't make my own literals in my config (I think). 
So should I make a PR into this repository and then make a PR into the nvim repository of treesitter so that it could be enabled in my nvim?

**Comment by sogaiu** [comment]
@Invertisment For various reasons, at the moment I'm not inclined to change the grammar for this type of thing.

The following is for another lispish language that is somewhat along the lines of what you described:
```
; XXX: hack for things that might be from "elsewhere"
(
 (sym_lit) @property
 (.match? @property "^.*/.*$")
)
```
That ends up highlighting the text of the entire symbol though.

I don't know if nvim-treesitter supports highlighting a portion of something that was matched, but perhaps nvim-treesitter folks would know better or may be changes could be made there or customizations provided that could make this kind of thing possible.

**Comment by Invertisment** [comment]
Nah, I'll probably stick to using the regex-based one as I already have my highlighting set up there. I was mostly wondering if it's better. And looks like it doesn't offer more than the default one. Maybe performance but I'm on nvim and probably it runs in background anyway.

**Comment by sogaiu** [comment]
My impression has been that tree-sitter doesn't really improve things overall for highlighting for lispish languages -- at least not currently.

I'm going to close this issue for now -- it can be reopened if necessary.

**Comment by sogaiu** [comment]
@dannyfreeman 

I agree it would be nice to be able to make such distinctions, but I'm unclear on whether it can be done well enough in the grammar without adversely impacting correctness -- difficulties I've encountered along these lines could often be traced to current tree-sitter capabilities as well as the lack of an appropriate specification for Clojure.

Verifying and supporting sufficient correctness has been one of the more time-consuming aspects of tree-sitter-clojure.  Most recently I've been using the method described [here](https://github.com/sogaiu/tree-sitter-clojure/blob/087bac78c53fe1387756cd5b8e68a69b3f6d7244/doc/testing.md#using-clojure-source-from-clojars).

There are also some [users of tree-sitter-clojure](https://github.com/sogaiu/tree-sitter-clojure/blob/087bac78c53fe1387756cd5b8e68a69b3f6d7244/doc/use.md) so considering potential consequences for them (may be at least nvim-treesitter, difftastic, and Cursorless) seems important.

For at least these reasons, I'm not keen on making changes that aren't fixes at this stage.

However, I'm not adverse to someone else trying :)

Would you like to take over tree-sitter-clojure?

**Comment by sogaiu** [comment]
@dannyfreeman 

> I will take some time to learn the grammar language and see if I can make sense of what exists in this repo now.

My tree-sitter and Clojure knowledge has been suffering from bit-rot but if you think there are questions you think I might be able to answer, I can try :)

> > Would you like to take over tree-sitter-clojure?

> I would need to give this some thought. I'm only about two days into working with tree sitter lol

Sounds good, no hurry on this end.

> maybe it would make sense to transfer ownership of this repo to the tree sitter org: https://github.com/tree-sitter. I had a little trouble figuring out that this was the most up to date grammar.

I can appreciate the point about discoverability.  However, I don't think the upstream tree-sitter folks are into taking over grammars -- IIUC, they are ok to list things that other folks are maintaining though (e.g. under [Available Parsers](https://tree-sitter.github.io/tree-sitter/#available-parsers)).  I did consider this, but having observed [this comment](https://github.com/tree-sitter/tree-sitter/issues/618#issuecomment-629549909) by one of the authors of a previous Clojure grammar attempt, I was reluctant to step on any toes so didn't pursue the matter.  (It may be a non-issue now, but I wasn't successful in contacting him earlier.)

Regarding language spec issues, there is a [notes.txt](https://github.com/sogaiu/tree-sitter-clojure/blob/087bac78c53fe1387756cd5b8e68a69b3f6d7244/notes.txt) file with some gathered bits along these lines (e.g. mention of [The Reader page at clojure.org](https://clojure.org/reference/reader) as well as some EDN bits).  Some portions may be out-of-date and it's a bit of a jumble, but FWIW.

On a side note, perhaps you are aware already, but FWIW, various nvim-treesitter contributors have done some neovim-specific work toward highlighting of Clojure code using the current grammar [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/clojure/highlights.scm).  I believe there are neovim-specific bits, but perhaps there are some tricks / techniques they've come up with that might be relevant for your Emacs-related activities.

**Comment by sogaiu** [comment]
> Fwiw, I think this repo would be the appropriate one to list since other tools are depending on it now.

I don't have a problem with having it listed -- though I don't feel comfortable being the one to make the request given the history.

> I've found a work around for the namespaced keyword highlighting

Glad to hear it :)

**Comment by sogaiu** [comment]
@dannyfreeman

BTW, I don't know if `clojure-ts-mode` would be affected, but there is [an outstanding issue](https://github.com/sogaiu/tree-sitter-clojure/issues/21) which hasn't been taken care of because I haven't succeeded in contacting relevant folks at nvim-treesitter to ascertain what consequences it might have for them.

If it ends up being a problem for your case, there is [a branch with a fix](https://github.com/sogaiu/tree-sitter-clojure/tree/issue-21) that might be relevant.

**Comment by NoahTheDuke** [comment]
I would like to voice my support for this change, as an nvim-treesitter user.

**Comment by sogaiu** [comment]
@dannyfreeman 

>  I can identify the other Clojure grammars and tag their maintainers in an issue somewhere in the tree sitter org. 

Ok, I see you did that in https://github.com/tree-sitter/tree-sitter/pull/1980

> I've updated my clojure-mode usage to work of that branch. It also fixed some issues I was having with metadata highlighting

Thanks for the report.

I'd like to apply some appropriate fix if practical, but I'll continue this line of thought at https://github.com/sogaiu/tree-sitter-clojure/issues/21

**Comment by sogaiu** [comment]
For the record, thanks to dannyfreeman's efforts in https://github.com/sogaiu/tree-sitter-clojure/pull/31, it should be possible to accomplish what was described in [the original description](https://github.com/sogaiu/tree-sitter-clojure/issues/28#issue-1354689729).

**Comment by oryband** [comment]
Can somebody please provide an example on how to chagne symbol and namespace highlighting in nvim so they will not be the same color as plain text?

**Comment by sogaiu** [comment]
I took a look at [nvim-treesitter's README](https://github.com/nvim-treesitter/nvim-treesitter#adding-queries) and found this:

> All queries found in the runtime directories will be combined. By convention, if you want to write a query, use the queries/ directory, but if you want to extend a query use the after/queries/ directory.

That info seemed to be incomplete though.  I found a bit in a discussion that seemed to provide sufficient info: https://github.com/nvim-treesitter/nvim-treesitter/discussions/3729#discussioncomment-3990282 [1].

I made a file at `after/queries/clojure/highlights.scm` with the following content:
```
;; extends
(sym_ns) @namespace

(sym_name) @symbol
```
That resulted in the namespace portion being highlighted differently from the name portion.

If that's not what you are after, it might still be that tweaking the content of a file in that location can lead to success.

---

[1] The missing piece was the `;; extends` comment.

**Comment by NoahTheDuke** [comment]
You have it right, @sogaiu. The only thing I can think is that the @oryband's colorscheme doesn't support treesitter highlighting groups.

**Comment by oryband** [comment]
I was using https://github.com/dracula/vim and have migrated to https://github.com/Mofiqul/dracula.nvim and the issue has been resolved

**Comment by sogaiu** [comment]
@NoahTheDuke Thanks for taking a look and commenting.

@oryband Glad to hear the issue has been resolved :)
