### ISSUE TITLE
String/Char parens are balanced with s-expr parenthesis

### ISSUE THREAD

**Issue by grierson** [sogaiu/tree-sitter-clojure#29]
String or Char parenthesis are balanced with s-expr parenthesis 

<img width="180" alt="Screenshot 2022-10-18 at 21 05 10" src="https://user-images.githubusercontent.com/1732552/196532816-36117fd3-8095-46e3-b142-e906ecab0693.png">
<img width="188" alt="Screenshot 2022-10-18 at 21 16 14" src="https://user-images.githubusercontent.com/1732552/196534945-dccac2c2-fd26-4927-8da3-69e7a4dccc55.png">

**Comment by grierson** [comment]
Thank you for taking a look

> Did you mean \) instead of /)?

Yes, sorry that was a typo :)

So for example the parentheses with a * before balance.

```clojure
(let [x *(str \*))
      y (list *["[]*]"])]
  (print (str y x)))
```

So when I press '%' to move to the matching brace it moves to commented brace instead of the s-expression brace.

> Are you by any chance using neovim and nvim-treesitter?

Yes, i'm using neovim and nvim-treesitter.

Thanks, I'll ask there too.

**Comment by sogaiu** [comment]
Thanks for the further investigation and report.

The issue you found at the nvim-treesitter repository does seem relevant.  Looking closely I see it mentions #22.

Does the suggestion at https://github.com/nvim-treesitter/nvim-treesitter/issues/2966#issuecomment-1140408607 help for your case?

**Comment by sogaiu** [comment]
It seems to me there is an issue elsewhere.

If that doesn't turn out to be the case, please re-open.
