### ISSUE TITLE
clojure syntax highlight queries

### ISSUE THREAD

**Issue by jasonjckn** [sogaiu/tree-sitter-clojure#30]
has anyone written clojure syntax highlight queries for emacs?

**Comment by sogaiu** [comment]
The only thing I'm aware of is the following thing modeled a bit after [tonsky's alabaster theme](https://github.com/tonsky/vscode-theme-alabaster):
```
(dis_expr) @comment

(kwd_lit) @type

(str_lit) @string

(num_lit) @number

[(bool_lit) (nil_lit)] @contant.builtin

(comment) @comment

;;(dis_expr) @comment

;; XXX
(regex_lit) @string.special
```
See [this](https://github.com/emacs-tree-sitter/elisp-tree-sitter/discussions/128) for background if interested.

**Comment by sogaiu** [comment]
@jasonjckn 

I understand that you're aware of the work on clojure-ts-mode, so I guess you're not looking for [what it does](https://github.com/dannyfreeman/clojure-mode/blob/b27d29c2773b61b39d5b9329a9b4e8944f1c1999/clojure-ts-mode.el#L187-L320).

I'm not sure what the future of elisp-tree-sitter is likely to be with the plan of upcoming versions of Emacs shipping with integrated tree-sitter support.  ATM, I only recall one person, @ag91,  who [used tree-sitter-clojure with Emacs + elisp-tree-sitter](https://ag91.github.io/blog/2021/06/22/how-(simple-is)-to-install-a-clojure-tree-sitter-grammar-and-use-it-from-emacs/).  Perhaps they had figured something out.

**Comment by jasonjckn** [comment]
feel free to close this issue, the thread on clojure mode is quite active now :)

**Comment by ag91** [comment]
yup sorry, I don't use it for highlighting but for editing/analysing code programmatically :)

**Comment by sogaiu** [comment]
@ag91 Thanks for chiming in.

On a slightly different note, @dannyfreeman has been working on #31 which we hope to be merging soon.  It should address #21 and #28.  I'm mentioning this as a heads-up as the grammar will be changing a bit as a result.  Hope that works out for the better for you.

**Comment by jasonjckn** [comment]
New clojure-ts-mode repo is @  https://github.com/clojure-emacs/clojure-ts-mode for anyone who finds this thread.

**Comment by sogaiu** [comment]
@ag91 and @NoahTheDuke any other interested parties

We're thinking to merge #31 around 2023-01-05 which is in about 2 weeks time.

Also, there's now a [potential changes announcements issue](https://github.com/sogaiu/tree-sitter-clojure/issues/33) where we hope to keep folks up-to-date about certain sorts of planned changes (though we don't expect many).  If you depend on tree-sitter-clojure in some way please have a look, and if it seems relevant to your situation, subscribe as well.

Thanks!
