### ISSUE TITLE
No tests to express expected failure for templates and other things

### ISSUE THREAD

**Issue by sogaiu** [sogaiu/tree-sitter-clojure#42]
There was a query about [how expected failures might be tested for](https://github.com/tree-sitter/tree-sitter/issues/2082) at the tree-sitter repository.

It got me thinking that we might be able to capture and express some of our intents about what we don't support.

Some possible examples of such things might include:

* template files that use `{{` and `}}` pairs
* ClojureCLR's [pipe-delimited symbols](https://github.com/sogaiu/tree-sitter-clojure/issues/35#issuecomment-1407320526)
* ~ClojureDart's new(?) [`#/` construct](https://github.com/sogaiu/tree-sitter-clojure/issues/35#issuecomment-1407319894)~ [1]

Additions based on further discussion:

* zero byte (based on discussion starting [here](https://github.com/sogaiu/tree-sitter-clojure/issues/42#issuecomment-1430117853)) - found [an additional source file that seems to use a zero byte](https://github.com/ont-app/vocabulary/blob/master/resources/uri-escapes.edn) -- 3rd byte

---

[1] I think we now know [what construct this is](https://github.com/sogaiu/tree-sitter-clojure/issues/46#issuecomment-1445515025) and ATM it seems reasonable to try to support it.

**Comment by sogaiu** [comment]
Below is an example corpus test for `{{`  `}}` templates:
```
================================================================================
Templates with `{{` `}}` Should Fail
================================================================================

(defproject codebrutale/{{name}} "0.1.0-SNAPSHOT"
  :description "FIXME"
  :url "https://github.com/codebrutale/{{name}}"
  :license {:name "Eclipse Public License"
            :url "https://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0"]])

--------------------------------------------------------------------------------

(source
  (list_lit
    (sym_lit
      (sym_name))
    (sym_lit
      (sym_name))
    (ERROR)
    (map_lit
      (map_lit
        (sym_lit
          (sym_name))))
    (str_lit)
    (kwd_lit
      (kwd_name))
    (str_lit)
    (kwd_lit
      (kwd_name))
    (str_lit)
    (kwd_lit
      (kwd_name))
    (map_lit
      (kwd_lit
        (kwd_name))
      (str_lit)
      (kwd_lit
        (kwd_name))
      (str_lit))
    (kwd_lit
      (kwd_name))
    (vec_lit
      (vec_lit
        (sym_lit
          (sym_ns)
          (sym_name))
        (str_lit)))))
```

**Comment by sogaiu** [comment]
Note the following [quote by the tree-sitter creator](https://github.com/tree-sitter/tree-sitter/issues/1870#issuecomment-1248659929):

> Yeah, there is intentionally not much that you as a grammar author can do to manipulate the error recovery.

Also, looking at the first comment in [this](https://github.com/tree-sitter/tree-sitter/issues/1993), it seems possible that tweaks to one's grammar might change whether and where there might be `ERROR` and/or `MISSING` nodes.

If that is the case, then having too many corpus tests that indicate precise failure patterns might not be so great from a maintenance perspective...

**Comment by sogaiu** [comment]
That sounds mostly good.

I want to document that we don't necessarily support some things though, like the items mentioned earlier.

If the testing could have been reliable, that would have been a bit more convenient.

**Comment by sogaiu** [comment]
Good point.

**Comment by sogaiu** [comment]
Ok, I'll update the initial post to include mention of zero bytes so there's a place we can look that fits on most normal screens :)

**Comment by sogaiu** [comment]
I added some preliminary expected failure testing in 51ca1432f561b38c444e87254d73a4464fb0658e (on the dev branch).

There isn't anything yet for ClojureCLR's pipe-delimited symbols, but I did add something for a template file that leads to a parse error and something for a file with a zero byte in it.

The tests can be invoked by `bb expect-failures`.

Not crazy about the output but at least the testing occurs.

On a related note, I experimented with using TAP in tree-sitter-janet-simple as mentioned at the bottom of https://github.com/sogaiu/tree-sitter-clojure/issues/39#issuecomment-1442794350 (see the link named "described here").  I'm avoiding putting the link here because then this issue will show up at the tree-sitter repository unnecessarily :P

**Comment by sogaiu** [comment]
For the ClojureCLJ pipe-delimited symbol testing, it's not necessarily that we get an error parsing, it's that the parsed result may be quite different from correct.

[Here](https://github.com/sogaiu/tree-sitter-clojure/issues/35#issuecomment-1407698887) is a comment that has an example along with the resulting parse output.

Testing for that would be different from the other two things where there was checking for an exit code of 1 (possibly parsing the output to look for `ERROR` would be good too, but that's not there ATM).

**Comment by sogaiu** [comment]
Thanks for trying things out.

I think that:
```
|System.Collections.Generic.IList`1[System.Int32]|
```
is supposed to be a single symbol.

Via the command line I get:
```
$ rlwrap clojure
Clojure 1.11.1
user=> '|System.Collections.Generic.IList`1[System.Int32]|
|System.Collections.Generic.IList
1
Syntax error (ClassNotFoundException) compiling at (REPL:0:0).
System.Int32
Syntax error compiling at (REPL:0:0).
Unable to resolve symbol: | in this context
user=>
```

I think what's happening here is that:

* `|System.Collections.Generic.IList` is recognized as a symbol [1]
* `1` is recognized as a number
* `[System.Int32]` is recognized as a vector with a single symbol in it
* The last `|` is being interpreted as a symbol

The ClojureCLR docs [here](https://github.com/clojure/clojure-clr/wiki/Specifying-types) have this bit:

> Vertical bars are used in pairs to surround the name (or part of the name) of a symbol that has any special characters (from the standard Clojure symbol viewpoint) in it. For example, |A(B)|, A|(|B|)|, and A|(B)| all mean the symbol whose name consists of the four characters A, (, B, and ).

So the parsing doesn't seem correct to me.

I suspect if this is to be handled that doing it via an external scanner might be worth considering.  I'm not yet convinced effort should be spent on it at this stage though.

---

[1] I tried the following too:
```
$ rlwrap clojure
Clojure 1.11.1
user=> (def |System.Collections.Generic.IList 1)
#'user/|System.Collections.Generic.IList
```
so that seems to be evidence in favor of `|System.Collections.Generic.IList` being interpreted as a symbol.

**Comment by NoahTheDuke** [comment]
@dmiller might have thoughts here. I know he's currently in the process of rewriting the ClojureCLR in F#, maybe he'd be willing to shed some insights on this stuff for us. If the cljr community can move to relying on a different filetype, we could help fork this for them. Otherwise, I agree we're at an impasse.

**Comment by dmiller** [comment]
I'm not sure of all the questions being asked, but here goes from what I can figure out.
The |...| syntax I would love to see going away in the rewrite, but unfortunately I may need to keep it for backward compatibility.
If tagged literals had been available at the time, I would have used them instead of | ... |, but so it goes.

Regarding |System.Collections.Generic.IList`1[System.Int32]|  -- this unfortunately is the actual CLR name for the type.
I didn't know what kind of sweetened syntax to put in for typenames, a la C# or F# -- no experience in the real world at that point -- so i went with the official CLR syntax.  Given all the strange characters, I had to introduce | ... | quoting for symbol names.  Stolen with some modification from Common Lisp.

How JVM handles it -- well, you can see it is weird.

Does this help?

**Comment by dmiller** [comment]
The plan is to move to a new extension .cljr.
The code to do that is in the latest alpha release of ClojureCLR (the current version, not the rewrite).
I will make that transition in all the libraries I maintain by the next release.
Though I'm sure folks will be happy enough to have any support and can live with some strange syntax highlighting.

**Comment by sogaiu** [comment]
In c86581f1b2fcc64d107a8f5f628cd7d829a3943f [1] I've added a babashka task to demonstrate an expected misparse.

`bb show-expected-misparses` should produce some output.  Not that illustrative at the moment.  Probbably it could use some work, but at least something is recorded in a way that can be checked programmatically.

---

[1] This is on a temporary branch where I'm working on various babashka tasks.

**Comment by sogaiu** [comment]
Most (if not all) of the testing for these bits will be living in [a separate repository](https://github.com/sogaiu/ts-clojure), so I'll close this issue for now.

Thanks to all the participants!
