### ISSUE TITLE
adding tree-sitter-clojure to crates.io

### ISSUE THREAD

**Issue by McPatate** [sogaiu/tree-sitter-clojure#54]
Hello, I see that you have a rust binding in your repo.

I can't seem to find it on crates.io, would it possible to add it there?

Thanks

**Comment by sogaiu** [comment]
At the moment our plan is to remove the bindings for various reasons.

There is some [documentation](https://github.com/sogaiu/tree-sitter-clojure/blob/master/doc/what-and-why.md#other-content) on how to generate them though.
