### ISSUE TITLE
Build failure on macOS 14.12.1 (Apple Silicon)

### ISSUE THREAD

**Issue by cocona20xx** [sogaiu/tree-sitter-clojure#55]
Not sure if this is an issue with something in the https://github.com/cursorless-dev/vscode-parse-tree buildscripts or on this project's end (or just a mistake I made somewhere when setting things up, could easily be that!), but the build failure occurs within this project's buildscripts so I'm posting it here:

Full build failure log: https://paste.ee/p/ZZvBj
The notable part appears to be the following:
```
In file included from ../bindings/node/binding.cc:3:
In file included from ../node_modules/nan/nan.h:176:
../node_modules/nan/nan_callbacks.h:55:23: error: no member named 'AccessorSignature' in namespace 'v8'
typedef v8::Local<v8::AccessorSignature> Sig;
                  ~~~~^
In file included from ../bindings/node/binding.cc:3:
../node_modules/nan/nan.h:2542:8: error: no matching member function for call to 'SetAccessor'
  tpl->SetAccessor(
  ~~~~~^~~~~~~~~~~
/Users/cocona20xx/Library/Caches/node-gyp/21.5.0/include/node/v8-template.h:816:8: note: candidate function not viable: no known conversion from 'imp::Sig' (aka 'int') to 'SideEffectType' for 7th argument
  void SetAccessor(
       ^
/Users/cocona20xx/Library/Caches/node-gyp/21.5.0/include/node/v8-template.h:809:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'AccessorGetterCallback' (aka 'void (*)(Local<String>, const PropertyCallbackInfo<Value> &)') for 2nd argument
  void SetAccessor(
       ^
In file included from ../bindings/node/binding.cc:2:
In file included from /Users/cocona20xx/Library/Caches/node-gyp/21.5.0/include/node/node.h:73:
In file included from /Users/cocona20xx/Library/Caches/node-gyp/21.5.0/include/node/v8.h:24:
In file included from /Users/cocona20xx/Library/Caches/node-gyp/21.5.0/include/node/v8-array-buffer.h:12:
/Users/cocona20xx/Library/Caches/node-gyp/21.5.0/include/node/v8-local-handle.h:253:5: error: static assertion failed due to requirement 'std::is_base_of<v8::Value, v8::Data>::value': type check
    static_assert(std::is_base_of<T, S>::value, "type check");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan_callbacks_12_inl.h:175:20: note: in instantiation of function template specialization 'v8::Local<v8::Value>::Local<v8::Data>' requested here
      cbinfo(info, obj->GetInternalField(kDataIndex));
                   ^
3 errors generated.
make: *** [Release/obj.target/tree_sitter_clojure_binding/bindings/node/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/Cellar/node/21.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Darwin 23.2.0
gyp ERR! command "/opt/homebrew/Cellar/node/21.5.0/bin/node" "/opt/homebrew/Cellar/node/21.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cocona20xx/vscode-parse-tree/node_modules/tree-sitter-clojure
```
I wonder if this has something to do with using homebrew for njs installation? Not sure why that'd cause issues, though.

Note that the version of emsdk used is `3.1.37`, as that appears to be the newest version that is known to work with tree-sitter.

**Comment by sogaiu** [comment]
Sorry, I don't have access to appropriate hardware (or the associated OS) to investigate directly.

I did find:

* https://github.com/nodejs/nan/issues/942
* https://github.com/electron/electron/issues/35193#issuecomment-1204143737

though, perhaps there is something relevant within.

Also, it might be that some of the info [here](https://github.com/sogaiu/tree-sitter-clojure/blob/6e41628e9d18b19caea1cb1d72aae4ccff5bdfe9/doc/what-and-why.md#nodejs-bindings) could be useful.  (Note that our current plan is to be removing bindings files and directories before long -- likely a bit after the next tree-sitter release.)

---

A few extra bits for reference follow.

Regarding emsdk and tree-sitter, if you haven't seen [this](https://github.com/sogaiu/ts-questions/blob/master/questions/which-version-of-emscripten-should-be-used-for-the-playground/README.md) already (the Versions section may be the most relevant), please have a look.

Also, concerning tree-sitter and homebrew, it might be worth being aware of [this conversation](https://github.com/tree-sitter/tree-sitter/issues/2803).

**Comment by sogaiu** [comment]
Going to close this for now.

For historical reference, please see [this comment](https://github.com/cursorless-dev/vscode-parse-tree/issues/76#issuecomment-1869417580) and [this comment](https://github.com/cursorless-dev/vscode-parse-tree/issues/76#issuecomment-1869724148).

Depending on how things evolve, this issue can be re-opened / revisited.
