### ISSUE TITLE
Version 0.0.13 is mostly ready but is not released

### ISSUE THREAD

**Issue by sogaiu** [sogaiu/tree-sitter-clojure#57]
Now that [tree-sitter 0.20.9 has been released](https://github.com/tree-sitter/tree-sitter/releases) perhaps it's good to move toward releasing [0.0.13](https://github.com/sogaiu/tree-sitter-clojure/blob/08b00c0e6e61f7c5650f8b3e2046b9f0fa1503c4/CHANGELOG.md#v0013---2023-10-xx) (see this link for a reminder of what we had planned on before).

I have run various tests (against the corpus and our large collection of samples) using tree-sitter 0.20.9 on the [post-0.0.12 branch](https://github.com/sogaiu/tree-sitter-clojure/tree/post-0.0.12) and found no unexpected issues.

Since it has been a while since the last tree-sitter release, I suppose it might not be surprising if issues with it surface.

I was going to suggest waiting a bit before releasing 0.0.13, but may be moving forward with making an announcement at https://github.com/sogaiu/tree-sitter-clojure/issues/33 is fine as we've typically waited about 2 weeks after announcing to actually release.

If some issue turns up during those 2 weeks we can revisit our plans.

@dannyfreeman Any thoughts?

_Update_: there is now a [pre-0.0.13](https://github.com/sogaiu/tree-sitter-clojure/tree/pre-0.0.13) branch.

**Comment by NoahTheDuke** [comment]
I don't think anyone will be annoyed by you waiting a bit to see how the dust settles.

**Comment by sogaiu** [comment]
Thanks a lot for the offer, highly appreciated!

I don't think we're in a hurry to release soon -- the stated date in the announcement is only an initial target.  If it happens we are ready then, we'll go ahead, otherwise we can postpone.

**Comment by sogaiu** [comment]
On a side note, a [new issue titled "Tree-Sitter Roadmap"](https://github.com/tree-sitter/tree-sitter/issues/2895) showed up at the tree-sitter repository.

Might be worth scanning to see what's on the minds of the maintainers...

Of note is [one of dannyfreeman's issues](https://github.com/tree-sitter/tree-sitter/issues/2611) titled "Grammar versions and dealing with breaking changes".  This is listed under the "Issues to tackle" section of the planned release of 0.20.10 in April of this year.

The following text was also present:

> For those reading this that wish to help out or move any issue they'd like fixed or feature they'd like implemented, don't hesitate! Draft a PR, ask questions, or reach out in the [discord](https://discord.gg/w7nTvsVJhm) to chat more! Any help is appreciated as long as it's high quality and well-thought-out.

Perhaps it includes pointing out issues that aren't listed on that page?  [This issue](https://github.com/tree-sitter/tree-sitter/issues/2012) doesn't appear to be listed and it came up for us [here](https://github.com/sogaiu/tree-sitter-clojure/issues/32).

**Comment by sogaiu** [comment]
@dannyfreeman Sorry to bug you.  Did you happen to have time to take a look?

**Comment by sogaiu** [comment]
For reference, [tree-sitter 0.21.0 was released](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.21.0).

It looks like [the default API level is still 14](https://github.com/tree-sitter/tree-sitter/blob/v0.21.0/lib/include/tree_sitter/api.h#L27).

There's a changelog [here](https://github.com/tree-sitter/tree-sitter/blob/d59f950005e33e5c5b0f39e0983938531da1d67d/CHANGELOG.md#0210--2024-02-21).

---

I am still inclined to release v0.0.13 based on tree-sitter 0.20.9 though.

**Comment by sogaiu** [comment]
Regarding:

> https://github.com/tree-sitter/tree-sitter/issues/2012 doesn't appear to be listed and it came up for us https://github.com/sogaiu/tree-sitter-clojure/issues/32.

I asked one of the maintainers and he said something to the effect that the desire to fix exists, but exactly what to do was not clear.

**Comment by sogaiu** [comment]
It looks like multiple releases have occurred since this issue was created (^^;

We're now up to [0.22.1](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.22.1).  The changelog is tiny for that, so might be better to look at [0.22.0](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.22.0), if interested in seeing what has changed.

---

Haven't digested the content in full, but one minor thing I noticed is:

> Remove top-level corpus dir for tests
> The cli will now only look in test/corpus for tests

Good thing we changed that in [this commit](https://github.com/sogaiu/tree-sitter-clojure/commit/df16f9366d365c1767f0e29a545281cb2de7b9c8).

**Comment by sogaiu** [comment]
I've finally [tagged a release as v0.0.13](https://github.com/sogaiu/tree-sitter-clojure/releases/tag/v0.0.13).

Thanks for your patience :)

Hope things are going well for everyone.

**Comment by sogaiu** [comment]
Thanks for stopping by :)

> looks like you didn't regenerate with latest version of tree-sitter. did you want to do that?

No, not at this time.

I've been watching recent developments of tree-sitter and I don't feel it has reached what seems like a stable-ish version.  Multiple releases have been made in a fairly short period and they all still generate a `src/parser.c` file with a API number of 14 by default (like 0.20.9 does).

Did the latest version seem somehow better than what I used?  My impression is that there isn't anything significant to be gained by generating with a more recent version of the tree-sitter cli, but may be I missed something (^^;

**Comment by NoahTheDuke** [comment]
I don't think you missed anything, I just have a vague memory of that being a point of discussion a few months ago when you first started preparing for this release. Thought it better to double check. Thanks for the release!

**Comment by sogaiu** [comment]
Yeah, I agree it's good to confirm.

Thanks!
