### ISSUE TITLE
Syntax-related changes in Clojure 1.12 unverified

### ISSUE THREAD

**Issue by sogaiu** [sogaiu/tree-sitter-clojure#63]
There are at least two syntax-related changes planned for Clojure 1.12 it seems -- there may be more [1], but I'll start noting here what I've found.

* [:param-tags metadata](https://clojure.atlassian.net/browse/CLJ-2805)
    > A new metadata reader syntax makes it easier to attach param-tags metadata to member symbols. The metadata syntax ^[ ... ] will be read by the reader and applied to the target as the metadata ^{:param-tags [ ... ]} . This is analogous to ^Type reading as the metadata ^{:tag Type}.

* [Array class syntax](https://clojure.atlassian.net/browse/CLJ-2807)
    > Developers can now refer to an array class using a symbol of the form ComponentClass/#dimensions, eg String/2 refers to the class of a 2 dimensional array of Strings. Component classes can be fully-qualified classes, imported classes, or primitives. Array class syntax can be used as both type hints and values.

    > Examples: String/1, java.lang.String/1, long/2.

I haven't yet tested any of the above with the current grammar.

The param-tags thing seems to be lacking in concrete examples in the descriptions I've seen.  If anyone can locate some correctly functioning ones, I'd appreciate seeing them.  May be [this file](https://github.com/clojure/clojure/blob/48b1fe5b50d48603f2c1fbd38223a7284520d1ed/test/clojure/test_clojure/param_tags.clj) has some relevant bits...

---

[1] According to [this page](https://clojure.org/news/2024/08/03/clojure-1-12-0-rc1), [this page](https://github.com/clojure/clojure/blob/48b1fe5b50d48603f2c1fbd38223a7284520d1ed/changes.md#changes-to-clojure-in-version-1120) has "a complete list of 1.12.0 features and fixes".

It occurs to me that there might have been things in Clojure 1.11.x that have not been accounted for, though I'm not finding anything obvious starting [here](https://github.com/clojure/clojure/blob/48b1fe5b50d48603f2c1fbd38223a7284520d1ed/changes.md#changes-to-clojure-in-version-1114).

**Comment by sogaiu** [comment]
For "Array class syntax", I tried:

```clj
String/1
```

this parsed here as:

```
(source [0, 0] - [1, 0]
  (sym_lit [0, 0] - [0, 8]
    namespace: (sym_ns [0, 0] - [0, 6])
    name: (sym_name [0, 7] - [0, 8])))
```

**Comment by sogaiu** [comment]
For ":param-tags metadata", I tried:

```clj
;; https://github.com/clojure/clojure/blob/48b1fe5b50d48603f2c1fbd38223a7284520d1ed/test/clojure/test_clojure/param_tags.clj
^[] String/.toUpperCase
^[] java.lang.String/.toUpperCase
^[java.util.Locale] String/.toUpperCase
^[long] Math/abs
^[_ _] Tuple/create
^[long long] UUID/new
^[long long] java.util.UUID/new
^[String] String/new
^[java.util.Locale] String/.toUpperCase
^[Locale] String/.toUpperCase
^[String] String/.getBytes
^[] Long/.toString
```

this parsed here as:

```
(source [0, 0] - [13, 0]
  (comment [0, 0] - [1, 0])
  (sym_lit [1, 0] - [1, 23]
    meta: (meta_lit [1, 0] - [1, 3]
      value: (vec_lit [1, 1] - [1, 3]))
    namespace: (sym_ns [1, 4] - [1, 10])
    name: (sym_name [1, 11] - [1, 23]))
  (sym_lit [2, 0] - [2, 33]
    meta: (meta_lit [2, 0] - [2, 3]
      value: (vec_lit [2, 1] - [2, 3]))
    namespace: (sym_ns [2, 4] - [2, 20])
    name: (sym_name [2, 21] - [2, 33]))
  (sym_lit [3, 0] - [3, 39]
    meta: (meta_lit [3, 0] - [3, 19]
      value: (vec_lit [3, 1] - [3, 19]
        value: (sym_lit [3, 2] - [3, 18]
          name: (sym_name [3, 2] - [3, 18]))))
    namespace: (sym_ns [3, 20] - [3, 26])
    name: (sym_name [3, 27] - [3, 39]))
  (sym_lit [4, 0] - [4, 16]
    meta: (meta_lit [4, 0] - [4, 7]
      value: (vec_lit [4, 1] - [4, 7]
        value: (sym_lit [4, 2] - [4, 6]
          name: (sym_name [4, 2] - [4, 6]))))
    namespace: (sym_ns [4, 8] - [4, 12])
    name: (sym_name [4, 13] - [4, 16]))
  (sym_lit [5, 0] - [5, 19]
    meta: (meta_lit [5, 0] - [5, 6]
      value: (vec_lit [5, 1] - [5, 6]
        value: (sym_lit [5, 2] - [5, 3]
          name: (sym_name [5, 2] - [5, 3]))
        value: (sym_lit [5, 4] - [5, 5]
          name: (sym_name [5, 4] - [5, 5]))))
    namespace: (sym_ns [5, 7] - [5, 12])
    name: (sym_name [5, 13] - [5, 19]))
  (sym_lit [6, 0] - [6, 21]
    meta: (meta_lit [6, 0] - [6, 12]
      value: (vec_lit [6, 1] - [6, 12]
        value: (sym_lit [6, 2] - [6, 6]
          name: (sym_name [6, 2] - [6, 6]))
        value: (sym_lit [6, 7] - [6, 11]
          name: (sym_name [6, 7] - [6, 11]))))
    namespace: (sym_ns [6, 13] - [6, 17])
    name: (sym_name [6, 18] - [6, 21]))
  (sym_lit [7, 0] - [7, 31]
    meta: (meta_lit [7, 0] - [7, 12]
      value: (vec_lit [7, 1] - [7, 12]
        value: (sym_lit [7, 2] - [7, 6]
          name: (sym_name [7, 2] - [7, 6]))
        value: (sym_lit [7, 7] - [7, 11]
          name: (sym_name [7, 7] - [7, 11]))))
    namespace: (sym_ns [7, 13] - [7, 27])
    name: (sym_name [7, 28] - [7, 31]))
  (sym_lit [8, 0] - [8, 20]
    meta: (meta_lit [8, 0] - [8, 9]
      value: (vec_lit [8, 1] - [8, 9]
        value: (sym_lit [8, 2] - [8, 8]
          name: (sym_name [8, 2] - [8, 8]))))
    namespace: (sym_ns [8, 10] - [8, 16])
    name: (sym_name [8, 17] - [8, 20]))
  (sym_lit [9, 0] - [9, 39]
    meta: (meta_lit [9, 0] - [9, 19]
      value: (vec_lit [9, 1] - [9, 19]
        value: (sym_lit [9, 2] - [9, 18]
          name: (sym_name [9, 2] - [9, 18]))))
    namespace: (sym_ns [9, 20] - [9, 26])
    name: (sym_name [9, 27] - [9, 39]))
  (sym_lit [10, 0] - [10, 29]
    meta: (meta_lit [10, 0] - [10, 9]
      value: (vec_lit [10, 1] - [10, 9]
        value: (sym_lit [10, 2] - [10, 8]
          name: (sym_name [10, 2] - [10, 8]))))
    namespace: (sym_ns [10, 10] - [10, 16])
    name: (sym_name [10, 17] - [10, 29]))
  (sym_lit [11, 0] - [11, 26]
    meta: (meta_lit [11, 0] - [11, 9]
      value: (vec_lit [11, 1] - [11, 9]
        value: (sym_lit [11, 2] - [11, 8]
          name: (sym_name [11, 2] - [11, 8]))))
    namespace: (sym_ns [11, 10] - [11, 16])
    name: (sym_name [11, 17] - [11, 26]))
  (sym_lit [12, 0] - [12, 18]
    meta: (meta_lit [12, 0] - [12, 3]
      value: (vec_lit [12, 1] - [12, 3]))
    namespace: (sym_ns [12, 4] - [12, 8])
    name: (sym_name [12, 9] - [12, 18])))
```

**Comment by NoahTheDuke** [comment]
That all looks right to me. Not much needed to make it all work.

**Comment by sogaiu** [comment]
Yes, perhaps nothing needs to be done.

Thanks for taking a look :+1:

**Comment by sogaiu** [comment]
On a side note, I think we may have "prepared" for some of this change via [this issue](https://github.com/sogaiu/tree-sitter-clojure/issues/50).

**Comment by sogaiu** [comment]
Thanks for your thoughts.

Appreciated as always!

**Comment by sogaiu** [comment]
I'll close this for now.  Fingers crossed.

**Comment by sogaiu** [comment]
[This rewrite-clj issue](https://github.com/clj-commons/rewrite-clj/issues/279) has more examples and may have wider coverage.

In [the initial description](https://github.com/clj-commons/rewrite-clj/issues/279#issue-2358162355), there are four things mentioned at this time:

* Method Values
* Qualified Methods
* Param tags
* Array class syntax

I think we covered the last two in our discussion here.

The other two don't look problematic to me.
*

**Comment by sogaiu** [comment]
In retrospect, it might have been a good idea to add some tests that captured some of the new uses.

It's not too late to add some corpus tests now ofc :)
